### PR TITLE
speed test

### PR DESCRIPTION
**Pull request by zzk0**
TODO:

- [x] speed test can work locally
- [x] add xrt test
- [x] cpu test
- [x] clean temporary files
- [x] merge parse.py and speed.py
- [ ] add to ci (next pr)

### CODE REVIEW

**Comment by zzk0** [comment]
贴几组手动测试的结果：

CPU(Intel(R) Xeon(R) Gold 5218 CPU @ 2.30GHz):

|  模型   | infer/seconds  |
|  ----  | ----  |
| alexnet | x |
| efficientnet_b7 | x |
| mobilenet_v3_large | x |
| resnet50 | 1.6 |
| resnet101 | x |
| vgg19 | 0.4 |
| vit_base_patch16_224 | x |
| mlp_mixer_b16_224 | x |

CUDA(V100):

|  模型   | infer/seconds  |
|  ----  | ----  |
| alexnet | 638.6 |
| efficientnet_b7 | 37.2 |
| mobilenet_v3_large | 203.8 |
| resnet50 | 174.4 |
| resnet101 | 99.4 |
| vgg19 | 225 |
| vit_base_patch16_224 | 128.4 |
| mlp_mixer_b16_224 | 178.2 |

TensorRT(V100):

|  模型   | infer/seconds  |
|  ----  | ----  |
| alexnet | 701 |
| efficientnet_b7 | 49.4 |
| mobilenet_v3_large | 288 |
| resnet50 | 203.2 |
| resnet101 | 109.6 |
| vgg19 | 280.8 |
| vit_base_patch16_224 | 126.6 |
| mlp_mixer_b16_224 | 172 |

**Comment by zzk0** [comment]
使用 https://github.com/Oneflow-Inc/oneflow/pull/7666 的速度测试结果

CUDA(V100):
|  模型   | infer/seconds  |
|  ----  | ----  |
| alexnet | 522 |
| efficientnet_b7 | 34.4 |
| mobilenet_v3_large | 192.6 |
| resnet50 | 169.4 |
| resnet101 | 84 |
| vgg19 | 222.6 |
| vit_base_patch16_224 | 127.8 |
| mlp_mixer_b16_224 | 166.6 |


TensorRT(V100):
|  模型   | infer/seconds  |
|  ----  | ----  |
| alexnet | 727.6 |
| efficientnet_b7 | 46.6 |
| mobilenet_v3_large | 269.4 |
| resnet50 | 200.2 |
| resnet101 | 111.8 |
| vgg19 | 280.4 |
| vit_base_patch16_224 | 122.6 |
| mlp_mixer_b16_224 | 168.2 |

**Comment by zzk0** [comment]
使用 https://github.com/Oneflow-Inc/oneflow/pull/7666 的速度测试结果，FLAGS_clustering_minimum_nodes=6 的环境变量。

CUDA(V100):
|  模型   | infer/seconds  |
|  ----  | ----  |
| alexnet | 595.4 |
| efficientnet_b7 | 34 |
| mobilenet_v3_large | 177.2 |
| resnet50 | 166 |
| resnet101 | 98.8 |
| vgg19 | 218 |
| vit_base_patch16_224 | 123.6 |
| mlp_mixer_b16_224 | 172.8 |


TensorRT(V100):
|  模型   | infer/seconds  |
|  ----  | ----  |
| alexnet | 634.2 |
| efficientnet_b7 | 37 |
| mobilenet_v3_large | 180.6 |
| resnet50 | 191.4 |
| resnet101 | 106.6 |
| vgg19 | 277.6 |
| vit_base_patch16_224 | 128.2 |
| mlp_mixer_b16_224 | 173.6 |

**Comment by hjchen2** [comment]
把FLAGS_strict_clustering=0加上重新跑一下tensorrt的结果吧

**Comment by zzk0** [comment]
使用 https://github.com/Oneflow-Inc/oneflow/pull/7666 的速度测试结果，FLAGS_clustering_minimum_nodes=0 的环境变量。

CUDA(V100):
|  模型   | infer/seconds  |
|  ----  | ----  |
| alexnet | 553 |
| efficientnet_b7 | 37.6 |
| mobilenet_v3_large | 198.4 |
| resnet50 | 169.8 |
| resnet101 | 95.4 |
| vgg19 | 218.8 |
| vit_base_patch16_224 | 125.6 |
| mlp_mixer_b16_224 | 173.8 |


TensorRT(V100):
|  模型   | infer/seconds  |
|  ----  | ----  |
| alexnet | 720.6 |
| efficientnet_b7 | 47.8 |
| mobilenet_v3_large | 273.2 |
| resnet50 | 202.6 |
| resnet101 | 105.8 |
| vgg19 | 277.8 |
| vit_base_patch16_224 | 121 |
| mlp_mixer_b16_224 | 163 |

**Comment by zzk0** [comment]
OpenVINO 测速失败报错：

```
I0330 02:07:27.212769 1 infer_request.cc:524] prepared: [0x0x7ff078010d80] request id: , model: efficientnet_b7, requested version: -1, actual version: 1, flags: 0x0, correlation id: 0, batch size: 0, priority: 0, timeout (us): 0
original inputs:
[0x0x7ff078012d98] input: INPUT_0, type: FP32, original shape: [1,3,224,224], batch + shape: [1,3,224,224], shape: [1,3,224,224]
override inputs:
inputs:
[0x0x7ff078012d98] input: INPUT_0, type: FP32, original shape: [1,3,224,224], batch + shape: [1,3,224,224], shape: [1,3,224,224]
original requested outputs:
OUTPUT_0
requested outputs:
OUTPUT_0

I0330 02:07:27.212897 1 oneflow.cpp:269] model efficientnet_b7, instance efficientnet_b7_0, executing 1 requests
I0330 02:07:27.212936 1 model_instance_state.cpp:96] TRITONBACKEND_ModelExecute: Running efficientnet_b7_0 with 1 requests
terminate called after throwing an instance of 'ngraph::NodeValidationFailure'
  what():  Check 'Dimension::merge(merged_channel_count, data_channel_count, filter_input_channel_count)' failed at core/src/validation_util.cpp:430:
While validating node 'v1::Convolution Convolution_893 (Parameter_891[0]:f32{1,64,112,112}, Constant_892[0]:f32{64,1,3,3}) -> (dynamic?)' with friendly_name 'Convolution_893':
Data batch channel count (64) does not match filter input channel count (1).

Signal (6) received.
```

**Comment by zzk0** [comment]
CPU None:
| Model | Concurrency(1) | Concurrency(2) | Concurrency(3) | Concurrency(4) |
| ---- | ----  | ---- | ---- | ---- |
| alexnet | 9.8(122572) | 10.6(225683) | 10.6(319596) | 10(428973) |  
| mobilenet_v3_large | x | x | x | x |  
| resnet50 | x | x | x | x |  
| resnet101 | x | x | x | x |  
| vgg19 | 0.6(1698508) | 0.6(3057821) | 0.4(4618831) | 0.4(5912283) |  
| vit_base_patch16_224 | x | x | x | x |  
| mlp_mixer_b16_224 | x | x | x | x |  

CPU openvino:
| Model | Concurrency(1) | Concurrency(2) | Concurrency(3) | Concurrency(4) |
| ---- | ----  | ---- | ---- | ---- |
| alexnet | 28.6(44195) | 30.8(71840) | 30.2(112344) | 30(149969) |  
| mobilenet_v3_large | x | x | x | x |  
| resnet50 | 26.4(46437) | 27.4(85178) | 28.2(124112) | 27.6(164477) |  
| resnet101 | 23.8(48547) | 25.4(88838) | 25(130604) | 25.6(166960) |  
| vgg19 | 3.6(333938) | 3.6(569710) | 3.8(867763) | 3.6(1100510) |  
| vit_base_patch16_224 | x | x | x | x |  
| mlp_mixer_b16_224 | x | x | x | x |  

CUDA None:
| Model | Concurrency(1) | Concurrency(2) | Concurrency(3) | Concurrency(4) |
| ---- | ----  | ---- | ---- | ---- |
| alexnet | 288(3839) | 514.4(4372) | 522.6(6480) | 510(8556) |  
| mobilenet_v3_large | 140(10056) | 219.4(15524) | 215.8(23051) | 224.6(27964) |  
| resnet50 | 128.2(11039) | 176.8(17683) | 180(25287) | 175(33370) |  
| resnet101 | 95(16273) | 111(27017) | 106.2(39381) | 106(51362) |  
| vgg19 | 164.6(6525) | 219.6(9445) | 219.6(14195) | 219.4(18864) |  
| vit_base_patch16_224 | 106.2(9780) | 126.8(17505) | 126.8(26993) | 125.6(35888) |  
| mlp_mixer_b16_224 | 139.8(7461) | 177.4(11876) | 176.6(18354) | 177.8(23500) |  

CUDA tensorrt:
| Model | Concurrency(1) | Concurrency(2) | Concurrency(3) | Concurrency(4) |
| ---- | ----  | ---- | ---- | ---- |
| alexnet | 338.2(3223) | 641.8(3407) | 656.2(5018) | 652.2(6649) |  
| mobilenet_v3_large | 165.4(7485) | 267.6(11849) | 279(17355) | 259.6(22864) |  
| resnet50 | 172(6165) | 230.2(9195) | 231.2(13720) | 244.6(18197) |  
| resnet101 | 106.4(11031) | 128.2(18991) | 130.6(24975) | 129.6(34330) |  
| vgg19 | 193.4(5345) | 270.6(7670) | 272.4(11449) | 273.4(15086) |  
| vit_base_patch16_224 | 105.6(10793) | 122(20044) | 124.6(27192) | 124.8(35915) |  
| mlp_mixer_b16_224 | 134.6(8082) | 172.4(12597) | 173.2(18595) | 174.4(24779) |

**Review by mosout — APPROVED** [review]

**Comment by zzk0** [comment]
开启 openvino 后，有几个模型运行时候出错：efficientnet_b7, mobilenet_v3_large，vit_base_patch16_224_repo，mlp_mixer_b16_224_repo

## 报错信息

**efficientnet_b7**

```
root@abea9a361e34:/home/percent1/code/openvino_demo# ./build/classifier /home/percent1/code/serving_speed_test/repos/efficientnet_b7_repo/efficientnet_b7/1/model/ 1
terminate called after throwing an instance of 'ngraph::NodeValidationFailure'
  what():  Check 'Dimension::merge(merged_channel_count, data_channel_count, filter_input_channel_count)' failed at core/src/validation_util.cpp:430:
While validating node 'v1::Convolution Convolution_893 (Parameter_891[0]:f32{1,64,112,112}, Constant_892[0]:f32{64,1,3,3}) -> (dynamic?)' with friendly_name 'Convolution_893':
Data batch channel count (64) does not match filter input channel count (1).

Aborted (core dumped)
```

**mobilenet_v3_large**

```
root@abea9a361e34:/home/percent1/code/openvino_demo# ./build/classifier /home/percent1/code/serving_speed_test/repos/mobilenet_v3_large_repo/mobilenet_v3_large/1/model/ 1
terminate called after throwing an instance of 'ngraph::NodeValidationFailure'
  what():  Check 'Dimension::merge(merged_channel_count, data_channel_count, filter_input_channel_count)' failed at core/src/validation_util.cpp:430:
While validating node 'v1::Convolution Convolution_893 (Parameter_891[0]:f32{1,16,112,112}, Constant_892[0]:f32{16,1,3,3}) -> (dynamic?)' with friendly_name 'Convolution_893':
Data batch channel count (16) does not match filter input channel count (1).

Aborted (core dumped)
```

**vit_base_patch16_224**: 即使没开 openvino 也报错了，看着像是走到了一个 TODO

```
root@abea9a361e34:/home/percent1/code/openvino_demo# ./build/classifier /home/percent1/code/serving_speed_test/repos/vit_base_patch16_224_repo/vit_base_patch16_224/1/model/ 0
F20220401 03:16:53.656504 11595 layer_norm_cpu_kernel.cpp:28] TODO
*** Check failure stack trace: ***
    @     0x7fe5919dd253  google::LogMessage::Fail()
    @     0x7fe5919df844  google::LogMessage::SendToLog()
    @     0x7fe5919dcd3f  google::LogMessage::Flush()
    @     0x7fe5919dfe3f  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fe5c92e6bcf  oneflow::LayerNormCpuKernel<>::Compute()
    @     0x7fe5c7a28732  oneflow::UserKernel::ForwardUserKernel()
    @     0x7fe5c7a2880f  oneflow::UserKernel::ForwardDataContent()
    @     0x7fe5c79e8d6b  oneflow::Kernel::Forward()
    @     0x7fe5c79e920e  oneflow::Kernel::Launch()
    @     0x7fe5c7ac2781  oneflow::(anonymous namespace)::LightActor<>::ProcessMsg()
    @     0x7fe5c89144f7  oneflow::Thread::PollMsgChannel()
    @     0x7fe5c89146c8  _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZN7oneflow6ThreadC4ERKNS3_8StreamIdEEUlvE_EEEEE6_M_runEv
    @     0x7fe5cd2d5de4  (unknown)
    @     0x7fe5914f5609  start_thread
    @     0x7fe5cd114293  clone
Aborted (core dumped)
```

**mlp_mixer_b16_224_repo**：错误同上，不再列出。

**Comment by daquexian** [comment]
这些问题可以先记录下来，在 ci 里暂时不跑这些模型

**Comment by zzk0** [comment]
使用下面代码加载模型，并用 openvino 推理，可以复现上面的问题。
```
#include <chrono>
#include <cstdlib>
#include <iostream>
#include <oneflow/api.h>
#include <string>

class EnvScope { // NOLINT
public:
  EnvScope() { oneflow_api::initialize(); }
  ~EnvScope() { oneflow_api::release(); }
};

int main(int argc, char **argv) {
  if (argc != 3) {
    std::cout << "usage: classifier model_path enable_openvino[0|1]" << std::endl;
    return -1;
  }
  std::string model_name = std::string(argv[1]);
  bool enable_openvino = bool(std::atoi(argv[2]));

  EnvScope scope;
  oneflow_api::Device device("cpu");
  oneflow_api::Shape shape({1, 3, 224, 224});
  std::vector<float> ones(shape.elem_cnt(), 1.0f);
  std::vector<oneflow_api::Tensor> inputs{oneflow_api::Tensor::from_buffer(
      ones.data(), shape, device, oneflow_api::DType::kFloat)};
  oneflow_api::Graph graph = oneflow_api::Graph::Load(model_name, device);
  if (enable_openvino) {  
    graph.enable_openvino();
  }

  // warm up
  {
    const auto &value = graph.Forward(inputs);
    oneflow_api::Tensor output = value.ToTensor();
    std::vector<float> buf(output.shape().elem_cnt());
    output.copy_to(buf.data());
  }

  auto t0 = std::chrono::high_resolution_clock::now();
  for (int i = 0; i < 10; ++i) {
    const auto &value = graph.Forward(inputs);
    oneflow_api::Tensor output = value.ToTensor();
    std::vector<float> buf(output.shape().elem_cnt());
    output.copy_to(buf.data());
  }
  auto t1 = std::chrono::high_resolution_clock::now();
  std::cout << std::chrono::duration_cast<std::chrono::milliseconds>((t1 - t0))
                   .count()
            << std::endl;

  return 0;
}
```

仔细看 model.mlir 那个文件，报错的算子信息如下。如果使用 oneflow 进行推理，不会出错，使用 openvino 推理，就会报错。

```
    %2 = "oneflow.conv2d"(%1, %output_5) {data_format = "channels_first", device_name = ["@0:0"], device_tag = "gpu", dilation_rate = [1 : si32, 1 : si32], filters = 64 : si32, groups = 64 : si32, hierarchy = [1], kernel_size = [3 : si32, 3 : si32], op_name = "model.features.1.0.block.0.0-conv2d-3", operand_segment_sizes = dense<[1, 1, 0, 0]> : vector<4xi32>, output_lbns = ["model.features.1.0.block.0.0-conv2d-3/out_0"], padding_before = [1 : si32, 1 : si32], scope_symbol_id = 4611686018427863039 : i64, strides = [1 : si32, 1 : si32]} : (tensor<1x64x112x112xf32>, tensor<64x1x3x3xf32>) -> tensor<1x64x112x112xf32>
```

**Pull request merged**
